routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\PostRequestStatisticController;
use Illuminate\Support\Facades\Route;

Route::middleware('auth')->group(function () {
    Route::get('/', [ArticleController::class, 'index'])->name('article.index');

    Route::prefix('article')->name('article.')->group(function () {
        Route::get('create', [ArticleController::class, 'create'])->name('create');
        Route::get('{article:slug}', [ArticleController::class, 'show'])->name('show');
        Route::get('{article:slug}/edit', [ArticleController::class, 'edit'])->name('edit');

        Route::post('/', [ArticleController::class, 'store'])->name('store');
        Route::post('{article:slug}', [ArticleController::class, 'update'])->name('update');
    });

    Route::get('intruders', [PostRequestStatisticController::class, 'index']);
    Route::get('intruders/clear', [PostRequestStatisticController::class, 'clear']);
});

require __DIR__ . '/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    @forelse($articles as $article)
                        @include('articles.preview', $article)
                    @empty
                        There are no articles available. Do you want to <a class="font-bold text-blue-500" href="{{ route('article.create') }}">create a new one</a>?
                    @endforelse

                    {{ $articles->links() }}
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/messages.blade.php
@if($errors->any())
    @foreach ($errors->all() as $error)
        <div class="py-3 px-5 mb-5 rounded-lg text-gray-100 bg-red-500">
            {{ $error }}
        </div>
    @endforeach
@endif

@if (session()->has('success'))
    <div class="py-3 px-5 mb-5 rounded-lg text-gray-100 bg-green-500">
        {{ session()->get('success') }}
    </div>
@endif