routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\PostRequestStatisticController;
use Illuminate\Support\Facades\Route;

Route::middleware('auth')->group(function () {
    Route::get('/', [ArticleController::class, 'index'])->name('article.index');

    Route::prefix('article')->name('article.')->group(function () {
        Route::get('create', [ArticleController::class, 'create'])->name('create');
        Route::get('{article:slug}', [ArticleController::class, 'show'])->name('show');
        Route::get('{article:slug}/edit', [ArticleController::class, 'edit'])->name('edit');

        Route::post('/', [ArticleController::class, 'store'])->name('store');
        Route::post('{article:slug}', [ArticleController::class, 'update'])->name('update');
    });

    Route::get('intruders', [PostRequestStatisticController::class, 'index']);
    Route::get('intruders/clear', [PostRequestStatisticController::class, 'clear']);
});

require __DIR__ . '/auth.php';

app/Models/Article.php
<?php

namespace App\Models;

use App\Http\Requests\AuthorizedRequest;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;

class Article extends Model implements HasMedia
{
    use HasFactory, HasSlug, InteractsWithMedia;

    /**
     * @var string[]
     */
    protected $fillable = [
        'title',
        'content',
        'is_published',
        'publishing_at',
    ];

    /**
     * @var string[]
     */
    protected $casts = [
        'is_published' => 'boolean',
    ];

    /**
     * @var string[]
     */
    protected $dates = [
        'publishing_at'
    ];

    /**
     * Eager load relationships.
     *
     * @var string[]
     */
    protected $with = ['user'];

    /**
     * Default pagination 'per_page' parameter value.
     *
     * @var int
     */
    protected $perPage = 5;

    /**
     * @return BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return SlugOptions
     */
    public function getSlugOptions(): SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('title')
            ->saveSlugsTo('slug');
    }

    /**
     * Get model's REST-ful URL.
     *
     * @return string
     */
    public function url(): string
    {
        return url("article/{$this->slug}");
    }

    /**
     * Register 'image' collection for article.
     */
    public function registerMediaCollections(): void
    {
        $this
            ->addMediaCollection('image')
            ->singleFile();
    }

    /**
     * Register image conversions for different scenarios.
     */
    public function registerMediaConversions(Media $media = null): void
    {
        $this->addMediaConversion('default')
            ->width(1200)
            ->height(400);

        $this->addMediaConversion('preview')
            ->width(800)
            ->height(250)
            ->quality(100);
    }

    /**
     * Show if article can be publicly viewed.
     *
     * @return bool
     */
    public function isPublic(): bool
    {
        return $this->is_published;
    }

    /**
     * @return bool
     */
    public function isScheduled(): bool
    {
        return ! $this->isPublic() && $this->publishing_at !== null;
    }

    /**
     * Scope only visible articles.
     *
     * @param $query
     * @return Builder
     */
    public function scopePublic($query): Builder
    {
        return $query->where('is_published', true);
    }

    /**
     * Scope yet to be published articles.
     *
     * @param $query
     * @return Builder
     */
    public function scopeUnpublished($query): Builder
    {
        return $query->where('publishing_at', '!=', null);
    }

    /**
     * Schedule article for scheduled posting.
     *
     * @param string $datetime
     * @return $this
     */
    public function schedule(string $datetime): self
    {
        return tap($this)->update([
            'publishing_at' => Carbon::createFromFormat('d-m-Y H:i', $datetime)
        ]);
    }

    /**
     * Determine if article should be scheduled for later posting.
     *
     * @param AuthorizedRequest $request
     * @return bool
     */
    public function schedulingNeeded(AuthorizedRequest $request): bool
    {
        return ! $request->getPublishingStatus()
            && $request->exists('scheduled_datetime')
            && $request->get('scheduled_datetime') !== null;
    }

    /**
     * @return $this
     */
    public function publish(): self
    {
        return tap($this)->update([
            'publishing_at' => null,
            'is_published'  => true
        ]);
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreArticleRequest;
use App\Http\Requests\UpdateArticleRequest;
use App\Models\Article;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;
use Spatie\MediaLibrary\MediaCollections\Exceptions\FileDoesNotExist;
use Spatie\MediaLibrary\MediaCollections\Exceptions\FileIsTooBig;

class ArticleController extends Controller
{
    /**
     * @return View
     */
    public function index(): View
    {
        return view('dashboard', [
            'articles' => Article::latest()->paginate(),
        ]);
    }

    /**
     * @param Article $article
     * @return View
     */
    public function show(Article $article): View
    {
        return view('articles.show', compact('article'));
    }

    /**
     * @param Article $article
     * @return View
     * @throws AuthorizationException
     */
    public function edit(Article $article): View
    {
        $this->authorize('update', $article);

        return view('articles.edit', compact('article'));
    }

    /**
     * @return View
     */
    public function create(): View
    {
        return view('articles.create');
    }

    /**
     * @param StoreArticleRequest $request
     * @return RedirectResponse
     * @throws FileDoesNotExist
     * @throws FileIsTooBig
     */
    public function store(StoreArticleRequest $request): RedirectResponse
    {
        /** @var Article $article */
        $article = auth()->user()->articles()->create(
            array_merge($request->validated(), ['is_published' => $request->getPublishingStatus()])
        );

        if ($request->has('image')) {
            $article->addMediaFromRequest('image')
                ->toMediaCollection('image');
        }

        $message = "Article has been created!";


        if ($article->schedulingNeeded($request)) {
            $article->schedule($request->get('scheduled_datetime'));

            $message .= " It will be published {$article->publishing_at->diffForHumans()}";
        }

        session()->flash('success', $message);

        return redirect($article->url());
    }

    /**
     * @param UpdateArticleRequest $request
     * @param Article $article
     * @return RedirectResponse
     * @throws AuthorizationException
     * @throws FileDoesNotExist
     * @throws FileIsTooBig
     */
    public function update(UpdateArticleRequest $request, Article $article): RedirectResponse
    {
        $this->authorize('update', $article);

        $article->update(
            array_merge($request->validated(), ['is_published' => $request->getPublishingStatus()])
        );

        if ($article->isDirty('is_published') && $request->getPublishingStatus()) {
            // If article was scheduled and after update you manually publish it,
            // schedule should be cleaned from article.
            $article->update(['publishing_at' => null]);
        }

        if ($request->has('image')) {
            $article->addMediaFromRequest('image')
                ->toMediaCollection('image');
        }

        session()->flash('success', 'Article has been updated!');

        return redirect($article->url());
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/articles/create.blade.php
<x-app-layout>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <a class="block mb-5 text-blue-700" href="{{ route('article.index') }}" onclick="return confirm('Are you sure? Changes made will be lost.')">
                        &laquo; Back to article list
                    </a>

                    @include('messages')

                    <form action="{{ route('article.store') }}" method="post" enctype="multipart/form-data">
                        @csrf

                        <article>
                            <div class="article-header flex flex-col mb-4">
                                <label for="image">Article image <span class="text-sm">(recommended width: 1200px or less)</span></label>
                                <input type="file" id="image" name="image" accept="image/jpeg,image/png">
                            </div>

                            <div class="article-header flex flex-col mb-4">
                                <label for="title">Article title <span class="text-red-500">*</span></label>
                                <input type="text" name="title" id="title" class="w-full" placeholder="Your awesome article title...">
                            </div>

                            <div class="article-content mb-4">
                                <label for="content">Article content <span class="text-red-500">*</span></label>
                                <textarea name="content" id="content" rows="10" class="w-full"></textarea>
                            </div>

                            <div class="additional mb-4">
                                <label for="is_published" class="pr-2">Is this article publicly available?</label>
                                <input type="checkbox" name="is_published" id="is_published">
                            </div>

                            <div class="additional mb-4" id="datetime_block">
                                <label for="publication_datetime">Make public at (backspace/delete key to clean):</label>
                                <input id="datetime" name="scheduled_datetime" placeholder="Select date and time...">
                            </div>

                            <div class="legend">
                                <p><span class="text-red-500">*</span> Mandatory fields</p>
                            </div>
                        </article>
                        <div class="actions w-full flex justify-end">
                            <a href="{{ route('article.index') }}" onclick="return confirm('Are you sure? Changes made will be lost.')" class="rounded-lg text-white py-2 px-4 bg-red-500 hover:bg-red-600 focus:outline-none">Cancel</a>
                            <button type="submit" class="rounded-lg text-white ml-5 py-2 px-4 bg-blue-500 hover:bg-blue-600 focus:outline-none">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    @push('styles')
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    @endpush

    @push('scripts')
        <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    @endpush
</x-app-layout>

resources/views/articles/edit.blade.php
<x-app-layout>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <a class="block mb-5 text-blue-700" href="{{ route('article.index') }}">&laquo; Back to article</a>

                    @include('messages')

                    <form action="{{ route('article.update', $article) }}" method="post" enctype="multipart/form-data">
                        @csrf

                        <article>
                            <div class="article-header flex flex-col mb-4">
                                @if ($image = $article->getFirstMedia('image'))
                                    <img class="h-48 w-full mb-5 object-contain" src="{{ $image->getUrl('preview') }}" alt="{{ $article->title }}">
                                @endif
                                <label for="image">Article image <span class="text-sm">(recommended width: 1200px or less)</span></label>
                                <input type="file" id="image" name="image" accept="image/jpeg,image/png">
                            </div>

                            <div class="article-header flex flex-col mb-4">
                                <label for="title">Article title <span class="text-red-500">*</span></label>
                                <input type="text" name="title" id="title" class="w-full" value="{{ old('title', $article->title) }}">
                            </div>

                            <div class="article-content mb-4">
                                <label for="content">Article content <span class="text-red-500">*</span></label>
                                <textarea name="content" id="content" rows="10" class="w-full">{{ old('content', $article->content) }}</textarea>
                            </div>

                            <div class="additional mb-4">
                                <label for="is_published" class="pr-2">Is this article publicly available?</label>
                                <input type="checkbox" name="is_published" id="is_published" {{ $article->is_published ? 'checked' : '' }}>
                            </div>

                            <div class="legend">
                                <p><span class="text-red-500">*</span> Mandatory fields</p>
                            </div>
                        </article>
                        <div class="actions w-full flex justify-end">
                            <a href="{{ route('article.index') }}" onclick="return confirm('Are you sure? Changes made will be lost.')" class="rounded-lg text-white py-2 px-4 bg-red-500 hover:bg-red-600 focus:outline-none">Cancel</a>
                            <button type="submit" class="rounded-lg text-white ml-5 py-2 px-4 bg-blue-500 hover:bg-blue-600 focus:outline-none">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/articles/preview.blade.php
<article class="p-4 mb-3 border-b-2">
    <div class="article-header flex flex-col justify-between mb-4">
        @if ($image = $article->getFirstMedia('image'))
            <img class="h-48 w-full mb-5 object-cover" src="{{ $image->getUrl('preview') }}" alt="{{ $article->title }}">
        @endif
        <div>
            <a href="{{ $article->url() }}" class="text-xl font-bold">{{ $article->title }}</a>
            @if (! $article->isPublic())
                <span class="p-1 text-xs text-gray-100 bg-red-400 rounded-md">Not public</span>
            @endif
        </div>
        @if (! $article->isScheduled())
            <p>{{ $article->created_at->format('F j, Y') }}</p>
        @else
            <p>Publishing: {{ $article->publishing_at->diffForHumans() }}</p>
        @endif
    </div>
    <div class="article-content mb-2">{{ \Illuminate\Support\Str::words($article->content, 25) }}</div>
    <div class="article-footer flex justify-end">
        <div class="actions w-1/4 flex justify-between">
            @can('update', $article)
                <a class="hover:underline flex" href="{{ $article->url() . '/edit' }}">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                    </svg>
                    Edit article
                </a>
            @endcan
            <a class="pl-4 hover:underline flex" href="{{ $article->url() }}">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 20H5a2 2 0 01-2-2V6a2 2 0 012-2h10a2 2 0 012 2v1m2 13a2 2 0 01-2-2V7m2 13a2 2 0 002-2V9a2 2 0 00-2-2h-2m-4-3H9M7 16h6M7 8h6v4H7V8z" />
                </svg>
                Read further
            </a>
        </div>
    </div>
</article>

resources/views/articles/show.blade.php
<x-app-layout>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <a class="block mb-5 text-blue-700" href="{{ route('article.index') }}">&laquo;  Back to article list</a>

                    @include('messages')

                    <article>
                        @if ($image = $article->getFirstMedia('image'))
                            <img class="mb-5 object-cover h-96 w-full" src="{{ $image->getUrl('default') }}" alt="{{ $article->title }}">
                        @endif

                        <div class="article-header flex justify-between mb-4">
                            <h1 class="text-xl font-bold">{{ $article->title }}</h1>
                            <p class="flex">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                                </svg>
                                @if (! $article->isScheduled())
                                    {{ $article->created_at->format('F j, Y') }}
                                @else
                                    Publishing: {{ $article->publishing_at->diffForHumans() }}
                                @endif
                            </p>
                        </div>
                        <div class="article-content mb-4">
                            {{ $article->content }}
                        </div>
                        <div class="article-footer flex justify-end">
                            <div class="actions w-full flex justify-between align-middle">
                                @can('update', $article)
                                    <a href="{{ route('article.edit', ['article' => $article]) }}" class="flex rounded-lg text-white py-2 px-4 bg-blue-500 hover:bg-blue-600 focus:outline-non">
                                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                                        </svg>
                                        Edit
                                    </a>
                                @endcan
                                <span>By: {{ $article->user->name }}</span>
                            </div>
                        </div>
                    </article>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>